### PR TITLE
Use OS agnostic temp directory and delete temp files after use

### PR DESCRIPTION
**Pull request by Waldo1637**
The temp directory change allows the integration-tests to run successfully on Windows.
Also a few minor changes, using try-with-resources and condensing some loops.

### CODE REVIEW

**Comment by jon-bell** [comment]
Thanks for the contribution! I don't have a Windows machine, but with these changes does it now work on Windows? if so, I am shocked :) Thank you, too for the try-with-resource patches... we had been maintaining Java 6 comparability until last year-ish (and will likely be dropping Java 7 over the summer).

**Comment by jon-bell** [comment]
(If it does now work, can you also add a change to the relevant part of the README in your PR?)

**Comment by Waldo1637** [comment]
I am attaching an output log that perhaps you can double check to see if anything is missing, ([PhosphorWindows.log](https://github.com/gmu-swe/phosphor/files/4494091/PhosphorWindows.log)). It looks like the Phosphor build and integration-tests were successful but is the "microbench" supposed to do anything else? It doesn't look like it ran any tests but perhaps there is some configuration issue on my setup.

**Comment by Waldo1637** [comment]
I made the README changes. Also, I did get the microbench to run tests. Turns out I was just running the default profile instead of set-benchmark.

**Comment by jon-bell** [comment]
Thanks for the contribution!

**Pull request merged**
