### PR TITLE
Implemented disabling the branch not taken in control tracking

### PR DESCRIPTION
**Pull request by miguelvelezmj25**
The implementation is guarded by an option -withoutBranchNotTaken.

### CODE REVIEW

**Comment by jon-bell** [comment]
For completeness, can you also add an option in the Premain argument parser (for the case that Phosphor is used as a JavaAgent)?

**Comment by miguelvelezmj25** [comment]
Done.

Also, did I actually remove this behavior correctly? Through debugging, I pinpointed that the branch not taken behavior happens in TaintPassingMV.java. I also ran some local tests and obtained the behavior that I wanted with the new implementation. I just want to make sure that my assumptions is correct and that I do not have to modify other parts of the program.

**Comment by jon-bell** [comment]
I'd suggest also adding an early-return in TaintPassingMV's visitInsn at if (opcode == TaintUtils.FORCE_CTRL_STORE) if your flag is set. Otherwise yes, it looks complete.

**Comment by miguelvelezmj25** [comment]
Done.

Thanks.

**Pull request merged**
